name: linux cmake gcc

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      id: install_dependencies
      run: sudo apt-get update -qq && sudo apt-get -y install ninja-build libboost-all-dev

    - name: Configure
      id: configure
      run: cmake -G Ninja .

    - name: Compile
      id: compile
      run: cmake --build .

    - name: Build and run unit tests
      id: run_unit_tests
      run: cmake --build . --target check
